"""empty message

Revision ID: 411e73550e8a
Revises: 7169ce2120fb
Create Date: 2019-04-13 21:37:26.379524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411e73550e8a'
down_revision = '7169ce2120fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bandcamp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre_text', sa.String(), nullable=True),
    sa.Column('art_id', sa.String(), nullable=True),
    sa.Column('primary_text', sa.String(), nullable=True),
    sa.Column('secondary_text', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('file', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('favorite', 'artist')
    op.drop_column('popular', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('popular', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.add_column('favorite', sa.Column('artist', sa.VARCHAR(), nullable=True))
    op.drop_table('bandcamp')
    # ### end Alembic commands ###
