"""popular

Revision ID: 50340ff9a0b3
Revises: 3e7c56757ea4
Create Date: 2019-03-30 23:13:30.978722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50340ff9a0b3'
down_revision = '3e7c56757ea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('popular', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_popular_timestamp'), 'popular', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_popular_timestamp'), table_name='popular')
    op.drop_column('popular', 'timestamp')
    # ### end Alembic commands ###
