"""empty message

Revision ID: 7169ce2120fb
Revises: f27c195fd221
Create Date: 2019-04-13 21:29:50.627539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7169ce2120fb'
down_revision = 'f27c195fd221'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorite', 'artist')
    op.drop_column('popular', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('popular', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.add_column('favorite', sa.Column('artist', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
