"""empty message

Revision ID: 80f3c9032bb3
Revises: 411e73550e8a
Create Date: 2019-04-16 12:17:03.579960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80f3c9032bb3'
down_revision = '411e73550e8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorite', 'artist')
    op.drop_column('popular', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('popular', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.add_column('favorite', sa.Column('artist', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
