"""popular

Revision ID: 8bd5cd887a51
Revises: 50340ff9a0b3
Create Date: 2019-03-30 23:32:32.857093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd5cd887a51'
down_revision = '50340ff9a0b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_popular_timestamp', table_name='popular')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_popular_timestamp', 'popular', ['timestamp'], unique=False)
    # ### end Alembic commands ###
