"""empty message

Revision ID: 8f78eb618a35
Revises: 
Create Date: 2019-04-21 19:21:59.745303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f78eb618a35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_song')
    op.add_column('bandcamp', sa.Column('date_entry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bandcamp', 'date_entry')
    op.create_table('favorite_song',
    sa.Column('favorite_id', sa.INTEGER(), nullable=True),
    sa.Column('url', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['favorite_id'], ['user.id'], ),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###
