"""favorite

Revision ID: 93bd82fa1389
Revises: a204c5c8eeb7
Create Date: 2019-04-05 16:14:03.141108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93bd82fa1389'
down_revision = 'a204c5c8eeb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('song', sa.String(), nullable=True))
    op.drop_column('favorite', 'artist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('artist', sa.VARCHAR(), nullable=True))
    op.drop_column('favorite', 'song')
    # ### end Alembic commands ###
