"""popular

Revision ID: a204c5c8eeb7
Revises: 1b31cd402566
Create Date: 2019-03-31 00:09:35.750030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a204c5c8eeb7'
down_revision = '1b31cd402566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_popular_timestamp', table_name='popular')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_popular_timestamp', 'popular', ['timestamp'], unique=False)
    # ### end Alembic commands ###
