"""add unique at Favorite

Revision ID: a58586368690
Revises: 959a4fdb1319
Create Date: 2019-04-22 10:22:17.635566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a58586368690'
down_revision = '959a4fdb1319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_song')
    op.create_unique_constraint(None, 'favorite', ['song'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorite', type_='unique')
    op.create_table('favorite_song',
    sa.Column('favorite_id', sa.INTEGER(), nullable=True),
    sa.Column('url', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['favorite_id'], ['user.id'], ),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###
