"""empty message

Revision ID: f27c195fd221
Revises: 93bd82fa1389
Create Date: 2019-04-13 20:49:50.704115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f27c195fd221'
down_revision = '93bd82fa1389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bandcamp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre_text', sa.String(), nullable=True),
    sa.Column('art_id', sa.String(), nullable=True),
    sa.Column('primary_text', sa.String(), nullable=True),
    sa.Column('secondary_text', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('file', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_song',
    sa.Column('favorite_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['favorite_id'], ['user.id'], ),
    sa.UniqueConstraint('url')
    )
    op.drop_column('favorite', 'artist')
    op.drop_column('popular', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('popular', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.add_column('favorite', sa.Column('artist', sa.VARCHAR(), nullable=True))
    op.drop_table('favorite_song')
    op.drop_table('bandcamp')
    # ### end Alembic commands ###
